import typing
from typing import Optional

from pysqlsync.formation.mutation import Mutator
from pysqlsync.formation.object_types import Column

from .object_types import OracleColumn


class OracleMutator(Mutator):
    def mutate_column_stmt(self, source: Column, target: Column) -> Optional[str]:
        source_column = typing.cast(OracleColumn, source)
        target_column = typing.cast(OracleColumn, target)

        changes: list[str] = []
        if source_column.data_type != target_column.data_type:
            changes.append(str(target_column.data_type))
        if source_column.default != target_column.default:
            if target_column.default is not None:
                changes.append(f"DEFAULT {target_column.default_expr}")
            else:
                changes.append("DEFAULT NULL")
        if source_column.nullable != target_column.nullable:
            if not target_column.nullable:
                changes.append("NOT NULL")
            else:
                changes.append("NULL")
        if source_column.identity != target_column.identity:
            if target_column.identity:
                changes.append("GENERATED BY DEFAULT AS IDENTITY")
            else:
                changes.append("DROP IDENTITY")

        if changes:
            return f"MODIFY {source_column.name} {' '.join(changes)}"
        else:
            return None
